error CustomError {
  value: uint
}

fn throwCustomError(value: uint)

fn identity(value: int): int
